name: osgi_dart_workspace
publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  - packages/dart_osgi_api
  - packages/dart_osgi_framework
  - packages/dart_osgi_test
  - packages/sensor_bundles
